<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ColorCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datacolorcode = [
            ['name'=>'AliceBlue ','slug' => NULL,'hex_code' => '#F0F8FF','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'AntiqueWhite ','slug' => NULL,'hex_code' => '#FAEBD7','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Aqua ','slug' => NULL,'hex_code' => '#00FFFF','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Aquamarine ','slug' => NULL,'hex_code' => '#7FFFD4','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Blue','slug' => NULL,'hex_code' => '#0000FF','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Azure ','slug' => NULL,'hex_code' => '#F0FFFF','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Beige','slug' => NULL,'hex_code' => '#F5F5DC','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Bisque','slug' => NULL,'hex_code' => '#FFE4C4','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Black','slug' => NULL,'hex_code' => '#000000','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'BlanchedAlmond','slug' => NULL,'hex_code' => '#FFEBCD','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'BlueViolet','slug' => NULL,'hex_code' => '#8A2BE2','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Brown','slug' => NULL,'hex_code' => '#A52A2A','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'BurlyWood','slug' => NULL,'hex_code' => '#DEB887','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'CadetBlue','slug' => NULL,'hex_code' => '#5F9EA0','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Chartreuse','slug' => NULL,'hex_code' => '#7FFF00','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Chocolate','slug' => NULL,'hex_code' => '#D2691E','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Coral','slug' => NULL,'hex_code' => '#FF7F50','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'CornflowerBlue','slug' => NULL,'hex_code' => '#6495ED','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Cornsilk','slug' => NULL,'hex_code' => '#FFF8DC','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Crimson','slug' => NULL,'hex_code' => '#DC143C','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Cyan','slug' => NULL,'hex_code' => '#00FFFF','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkBlue','slug' => NULL,'hex_code' => '#00008B','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkCyan','slug' => NULL,'hex_code' => '#008B8B','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkGoldenRod','slug' => NULL,'hex_code' => '#B8860B','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkGray','slug' => NULL,'hex_code' => '#A9A9A9','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkGreen','slug' => NULL,'hex_code' => '#006400','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkKhaki','slug' => NULL,'hex_code' => '#BDB76B','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkMagenta','slug' => NULL,'hex_code' => '#8B008B','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkOliveGreen','slug' => NULL,'hex_code' => '#556B2F','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkOrange','slug' => NULL,'hex_code' => '#FF8C00','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkOrchid','slug' => NULL,'hex_code' => '#9932CC','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkRed','slug' => NULL,'hex_code' => '#8B0000','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkSalmon','slug' => NULL,'hex_code' => '#E9967A','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkSeaGreen','slug' => NULL,'hex_code' => '#8FBC8F','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkSlateBlue','slug' => NULL,'hex_code' => '#483D8B','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkSlateGray','slug' => NULL,'hex_code' => '#2F4F4F','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkTurquoise','slug' => NULL,'hex_code' => '#00CED1','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DarkViolet','slug' => NULL,'hex_code' => '#9400D3','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DeepPink','slug' => NULL,'hex_code' => '#FF1493','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DeepSkyBlue','slug' => NULL,'hex_code' => '#00BFFF','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DimGray','slug' => NULL,'hex_code' => '#696969','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'DodgerBlue','slug' => NULL,'hex_code' => '#1E90FF','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'FireBrick','slug' => NULL,'hex_code' => '#B22222','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'FloralWhite','slug' => NULL,'hex_code' => '#FFFAF0','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'ForestGreen','slug' => NULL,'hex_code' => '#228B22','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Fuchsia','slug' => NULL,'hex_code' => '#FF00FF','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Gainsboro','slug' => NULL,'hex_code' => '#DCDCDC','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'GhostWhite','slug' => NULL,'hex_code' => '#F8F8FF','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Gold','slug' => NULL,'hex_code' => '#FFD700','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'GoldenRod','slug' => NULL,'hex_code' => '#DAA520','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Gray','slug' => NULL,'hex_code' => '#808080','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Green','slug' => NULL,'hex_code' => '#008000','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'GreenYellow','slug' => NULL,'hex_code' => '#ADFF2F','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'HoneyDew','slug' => NULL,'hex_code' => '#F0FFF0','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'HotPink','slug' => NULL,'hex_code' => '#FF69B4','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'IndianRed','slug' => NULL,'hex_code' => '#CD5C5C','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Indigo','slug' => NULL,'hex_code' => '#4B0082','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Ivory','slug' => NULL,'hex_code' => '#FFFFF0','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Khaki','slug' => NULL,'hex_code' => '#F0E68C','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Lavender','slug' => NULL,'hex_code' => '#E6E6FA','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LavenderBlush','slug' => NULL,'hex_code' => '#FFF0F5','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LawnGreen','slug' => NULL,'hex_code' => '#7CFC00','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LemonChiffon','slug' => NULL,'hex_code' => '#FFFACD','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightBlue','slug' => NULL,'hex_code' => '#ADD8E6','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightCoral','slug' => NULL,'hex_code' => '#F08080','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightCyan','slug' => NULL,'hex_code' => '#E0FFFF','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightGoldenRodYellow','slug' => NULL,'hex_code' => '#FAFAD2','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightGray','slug' => NULL,'hex_code' => '#D3D3D3','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightGreen','slug' => NULL,'hex_code' => '#90EE90','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightPink','slug' => NULL,'hex_code' => '#FFB6C1','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightSalmon','slug' => NULL,'hex_code' => '#FFA07A','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightSeaGreen','slug' => NULL,'hex_code' => '#20B2AA','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightSkyBlue','slug' => NULL,'hex_code' => '#87CEFA','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightSlateGray','slug' => NULL,'hex_code' => '#778899','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightSteelBlue','slug' => NULL,'hex_code' => '#B0C4DE','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LightYellow','slug' => NULL,'hex_code' => '#FFFFE0','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Lime','slug' => NULL,'hex_code' => '#00FF00','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'LimeGreen','slug' => NULL,'hex_code' => '#32CD32','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Linen','slug' => NULL,'hex_code' => '#FAF0E6','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Magenta','slug' => NULL,'hex_code' => '#FF00FF','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Maroon','slug' => NULL,'hex_code' => '#800000','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'MediumAquaMarine','slug' => NULL,'hex_code' => '#66CDAA','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'MediumBlue','slug' => NULL,'hex_code' => '#0000CD','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'MediumOrchid','slug' => NULL,'hex_code' => '#BA55D3','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'MediumPurple','slug' => NULL,'hex_code' => '#9370DB','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'MediumSeaGreen','slug' => NULL,'hex_code' => '#3CB371','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'MediumSlateBlue','slug' => NULL,'hex_code' => '#7B68EE','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'MediumSpringGreen','slug' => NULL,'hex_code' => '#00FA9A','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'MediumTurquoise','slug' => NULL,'hex_code' => '#48D1CC','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'MediumVioletRed','slug' => NULL,'hex_code' => '#C71585','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'MidnightBlue','slug' => NULL,'hex_code' => '#191970','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'MintCream','slug' => NULL,'hex_code' => '#F5FFFA','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'MistyRose','slug' => NULL,'hex_code' => '#FFE4E1','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Moccasin','slug' => NULL,'hex_code' => '#FFE4B5','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'NavajoWhite','slug' => NULL,'hex_code' => '#FFDEAD','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Navy','slug' => NULL,'hex_code' => '#000080','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'OldLace','slug' => NULL,'hex_code' => '#FDF5E6','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Olive','slug' => NULL,'hex_code' => '#808000','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'OliveDrab','slug' => NULL,'hex_code' => '#6B8E23','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Orange','slug' => NULL,'hex_code' => '#FFA500','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'OrangeRed','slug' => NULL,'hex_code' => '#FF4500','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Orchid','slug' => NULL,'hex_code' => '#DA70D6','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'PaleGoldenRod','slug' => NULL,'hex_code' => '#EEE8AA','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'PaleGreen','slug' => NULL,'hex_code' => '#98FB98','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'PaleTurquoise','slug' => NULL,'hex_code' => '#AFEEEE','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'PaleVioletRed','slug' => NULL,'hex_code' => '#DB7093','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'PapayaWhip','slug' => NULL,'hex_code' => '#FFEFD5','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'PeachPuff','slug' => NULL,'hex_code' => '#FFDAB9','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Peru','slug' => NULL,'hex_code' => '#CD853F','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Pink','slug' => NULL,'hex_code' => '#FFC0CB','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Plum','slug' => NULL,'hex_code' => '#DDA0DD','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'PowderBlue','slug' => NULL,'hex_code' => '#B0E0E6','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Purple','slug' => NULL,'hex_code' => '#800080','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'RebeccaPurple','slug' => NULL,'hex_code' => '#663399','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Red','slug' => NULL,'hex_code' => '#FF0000','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'RosyBrown','slug' => NULL,'hex_code' => '#BC8F8F','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'RoyalBlue','slug' => NULL,'hex_code' => '#4169E1','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'SaddleBrown','slug' => NULL,'hex_code' => '#8B4513','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Salmon','slug' => NULL,'hex_code' => '#FA8072','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'SandyBrown','slug' => NULL,'hex_code' => '#F4A460','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'SeaGreen','slug' => NULL,'hex_code' => '#2E8B57','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'SeaShell','slug' => NULL,'hex_code' => '#FFF5EE','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Sienna','slug' => NULL,'hex_code' => '#A0522D','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Silver','slug' => NULL,'hex_code' => '#C0C0C0','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'SkyBlue','slug' => NULL,'hex_code' => '#87CEEB','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'SlateBlue','slug' => NULL,'hex_code' => '#6A5ACD','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'SlateGray','slug' => NULL,'hex_code' => '#708090','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Snow','slug' => NULL,'hex_code' => '#FFFAFA','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'SpringGreen','slug' => NULL,'hex_code' => '#00FF7F','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'SteelBlue','slug' => NULL,'hex_code' => '#4682B4','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Tan','slug' => NULL,'hex_code' => '#D2B48C','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Teal','slug' => NULL,'hex_code' => '#008080','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Thistle','slug' => NULL,'hex_code' => '#D8BFD8','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Tomato','slug' => NULL,'hex_code' => '#FF6347','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Turquoise','slug' => NULL,'hex_code' => '#40E0D0','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Violet','slug' => NULL,'hex_code' => '#EE82EE','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Wheat','slug' => NULL,'hex_code' => '#F5DEB3','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'White','slug' => NULL,'hex_code' => '#FFFFFF','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'WhiteSmoke','slug' => NULL,'hex_code' => '#F5F5F5','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'Yellow','slug' => NULL,'hex_code' => '#FFFF00','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['name'=>'YellowGreen','slug' => NULL,'hex_code' => '#9ACD32','isactive' => 1,'isdeleted' => 0,'created_at' => Carbon::now(),'updated_at' => Carbon::now()]
        ];

        DB::table('color_codes')->insert($datacolorcode);

    }
}
