<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IconSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $icon = [
            // ['name' =>'fe fe-activity','cheatsheet' => ''],
            // ['name' =>'fe fe-airplay','cheatsheet' => ''],
            // ['name' =>'fe fe-alert-circle','cheatsheet' => ''],
            // ['name' =>'fe fe-alert-octagon','cheatsheet' => ''],
            // ['name' =>'fe fe-alert-triangle','cheatsheet' => ''],
            // ['name' =>'fe fe-align-center','cheatsheet' => ''],
            // ['name' =>'fe fe-align-justify','cheatsheet' => ''],
            // ['name' =>'fe fe-align-left','cheatsheet' => ''],
            // ['name' =>'fe fe-align-right','cheatsheet' => ''],
            // ['name' =>'fe fe-anchor','cheatsheet' => ''],
            // ['name' =>'fe fe-aperture','cheatsheet' => ''],
            // ['name' =>'fe fe-arrow-down','cheatsheet' => ''],
            // ['name' =>'fe fe-arrow-down-circle','cheatsheet' => ''],
            // ['name' =>'fe fe-arrow-down-left','cheatsheet' => ''],
            // ['name' =>'fe fe-arrow-down-right','cheatsheet' => ''],
            // ['name' =>'fe fe-arrow-left','cheatsheet' => ''],
            // ['name' =>'fe fe-arrow-left-circle','cheatsheet' => ''],
            // ['name' =>'fe fe-arrow-right','cheatsheet' => ''],
            // ['name' =>'fe fe-arrow-right-circlei','cheatsheet' => ''],
            // ['name' =>'fe fe-arrow-up','cheatsheet' => ''],
            // ['name' =>'fe fe-arrow-up-circle','cheatsheet' => ''],
            // ['name' =>'fe fe-arrow-up-left','cheatsheet' => ''],
            // ['name' =>'fe fe-arrow-up-right ','cheatsheet' => ''],
            // ['name' =>'fe fe-at-sign','cheatsheet' => ''],
            // ['name' =>'fe fe-award','cheatsheet' => ''],
            // ['name' =>'fe fe-bar-chart','cheatsheet' => ''],
            // ['name' =>'fe fe-bar-chart-2','cheatsheet' => ''],
            // ['name' =>'fe fe-battery','cheatsheet' => ''],
            // ['name' =>'fe fe-battery-charging','cheatsheet' => ''],
            // ['name' =>'fe fe-bell','cheatsheet' => ''],
            // ['name' =>'fe fe-bell-off'],
            // ['name' =>'fe fe-bluetooth'],
            // ['name' =>'fe fe-bold'],
            // ['name' =>'fe fe-book'],
            // ['name' =>'fe fe-book-open'],
            // ['name' =>'fe fe-bookmark'],
            // ['name' =>'fe fe-boxfe'],
            // ['name' =>'fe-briefcase'],
            // ['name' =>'fe fe-calendar'],
            // ['name' =>'fe fe-camera'],
            // ['name' =>'fe fe-camera-off'],
            // ['name' =>'fe fe-cast'],
            // ['name' =>'fe fe-check'],
            // ['name' =>'fe fe-check-circle'],
            // ['name' =>'fe fe-check-square'],
            // ['name' =>'fe fe-chevron-down'],
            // ['name' =>'fe fe-chevron-left'],
            // ['name' =>'fe fe-chevron-right'],
            // ['name' =>'fe fe-chevron-up'],
            // ['name' =>'fe fe-chevrons-down'],
            // ['name' =>'fe fe-chevrons-left'],
            // ['name' =>'fe fe-chevrons-right'],
            // ['name' =>'fe fe-chevrons-up'],
            // ['name' =>'fe fe-chrome'],
            // ['name' =>'fe fe-circle'],
            // ['name' =>'fe fe-clipboard'],
            // ['name' =>'fe fe-clock'],
            // ['name' =>'fe fe-cloud'],
            // ['name' =>'fe fe-cloud-drizzle'],
            // ['name' =>'fe fe-cloud-lightning'],
            // ['name' =>'fe fe-cloud-off'],
            // ['name' =>'fe fe-cloud-rain'],
            // ['name' =>'fe fe-cloud-snow'],
            // ['name' =>'fe fe-code'],
            // ['name' =>'fe fe-codepen'],
            // ['name' =>'fe fe-command'],
            // ['name' =>'fe fe-compass'],
            // ['name' =>'fe fe-copy'],
            // ['name' =>'fe fe-corner-down-left'],
            // ['name' =>'fe fe-corner-down-right'],
            // ['name' =>'fe fe-corner-left-down'],
            // ['name' =>'fe fe-corner-left-up'],
            // ['name' =>'fe fe-corner-right-down'],
            // ['name' =>'fe fe-corner-right-up'],
            // ['name' =>' fe fe-corner-up-left'],
            // ['name' =>'fe fe-corner-up-right'],
            // ['name' =>'fe fe-cpufe'],
            // ['name' =>'fe-credit-card'],
            // ['name' =>'fe fe-crop'],
            // ['name' =>'fe fe-crosshair '],
            // ['name' =>'fe fe-database'],
            // ['name' =>'fe fe-delete'],
            // ['name' =>'fe fe-disc'],
            // ['name' =>'fe fe-dollar-sign'],
            // ['name' =>'fe fe-download'],
            // ['name' =>'fe fe-download-cloud'],
            // ['name' =>'fe fe-droplet'],
            // ['name' =>'fe fe-edit'],
            // ['name' =>'fe fe-edit-2 '],
            // ['name' =>'fe fe-edit-3'],
            // ['name' =>'fe fe-external-link'],
            // ['name' =>'fe fe-eye'],
            // ['name' =>'fe fe-eye-off'],
            // ['name' =>'fe fe-facebook'],
            // ['name' =>'fe fe-fast-forward'],
            // ['name' =>'fe fe-feather'],
            // ['name' =>' fe fe-file'],
            // ['name' =>'fe fe-file-minus'],
            // ['name' =>'fe fe-file-plus'],
            // ['name' =>'fe fe-file-text'],
            // ['name' =>'fe fe-film'],
            // ['name' =>'fe fe-filter'],
            // ['name' =>'fe fe-flag'],
            // ['name' =>'fe fe-folder'],
            // ['name' =>'fe fe-folder-minus'],
            // ['name' =>'fe fe-folder-plus'],
            // ['name' =>'fe fe-git-branch'],
            // ['name' =>'fe fe-git-commit'],
            // ['name' =>'fe fe-git-merge'],
            // ['name' =>'fe fe-git-pull-request'],
            // ['name' =>'fe fe-github'],
            // ['name' =>'fe fe-gitlab'],
            // ['name' =>'fe fe-globe'],
            // ['name' =>'fe fe-grid'],
            // ['name' =>'fe fe-hard-drive'],
            // ['name' =>'fe fe-hash'],
            // ['name' =>'fe fe-headphones'],
            // ['name' =>'fe fe-heart'],
            // ['name' =>'fe fe-help-circle'],
            // ['name' =>'fe fe-home'],
            // ['name' =>'fe fe-image'],
            // ['name' =>'fe fe-inbox'],
            // ['name' =>'fe fe-info'],
            // ['name' =>'fe fe-instagram'],
            // ['name' =>'fe fe-italic'],
            // ['name' =>'fe fe-layers'],
            // ['name' =>'fe fe-layout'],
            // ['name' =>'fe fe-life-buoy'],
            // ['name' =>'fe fe-link'],
            // ['name' =>'fe fe-link-2'],
            // ['name' =>'fe fe-linkedin'],
            // ['name' =>'fe fe-list'],
            // ['name' =>'fe fe-loader'],
            // ['name' =>'fe fe-lock'],
            // ['name' =>'fe fe-log-in'],
            // ['name' =>'fe fe-log-out'],
            // ['name' =>'fe fe-mail'],
            // ['name' =>'fe fe-map'],
            // ['name' =>'fe fe-map-pin'],
            // ['name' =>'fe fe-maximize'],
            // ['name' =>'fe fe-maximize-2'],
            // ['name' =>'fe fe-menu'],
            // ['name' =>'fe fe-message-circle'],
            // ['name' =>'fe fe-message-square'],
            // ['name' =>'fe fe-micfe fe-mic-off'],
            // ['name' =>'fe fe-minimize'],
            // ['name' =>'fe fe-minimize-2'],
            // ['name' =>'fe fe-minus'],
            // ['name' =>'fe fe-minus-circle '],
            // ['name' =>'fe fe-minus-square'],
            // ['name' =>'fe fe-monitor'],
            // ['name' =>'fe fe-moon'],
            // ['name' =>'fe fe-more-horizontal'],
            // ['name' =>'fe fe-more-vertical'],
            // ['name' =>'fe fe-move'],
            // ['name' =>'fe fe-music'],
            // ['name' =>'fe fe-navigation '],
            // ['name' =>'fe fe-navigation-2 '],
            // ['name' =>'fe fe-octagon'],
            // ['name' =>'fe fe-package'],
            // ['name' =>'fe fe-paperclip'],
            // ['name' =>'fe fe-pause'],
            // ['name' =>'fe fe-pause-circle'],
            // ['name' =>'fe fe-percent'],
            // ['name' =>'fe fe-phone'],
            // ['name' =>'fe fe-phone-call'],
            // ['name' =>'fe fe-phone-forwarded '],
            // ['name' =>'fe fe-phone-incoming'],
            // ['name' =>'fe fe-phone-missed'],
            // ['name' =>'fe fe-phone-off'],
            // ['name' =>'fe fe-phone-outgoing'],
            // ['name' =>'fe fe-pie-chart'],
            // ['name' =>'fe fe-play'],
            // ['name' =>'fe fe-play-circle'],
            // ['name' =>'fe fe-plus'],
            // ['name' =>'fe fe-plus-circle'],
            // ['name' =>'fe fe-plus-square'],
            // ['name' =>'fe fe-pocket'],
            // ['name' =>'fe fe-power'],
            // ['name' =>'fe fe-printer'],
            // ['name' =>'fe fe-radio'],
            // ['name' =>'fe fe-refresh-ccw'],
            // ['name' =>'fe fe-refresh-cw'],
            // ['name' =>'fe fe-repeat'],
            // ['name' =>'fe fe-rewind'],
            // ['name' =>'fe fe-rotate-ccw'],
            // ['name' =>'fe fe-rotate-cw'],
            // ['name' =>'fe fe-rss'],
            // ['name' =>'fe fe-save'],
            // ['name' =>'fe fe-scissors'],
            // ['name' =>'fe fe-search'],
            // ['name' =>'fe fe-send'],
            // ['name' =>'fe fe-server'],
            // ['name' =>'fe fe-settings'],
            // ['name' =>'fe fe-share'],
            // ['name' =>'fe fe-share-2'],
            // ['name' =>'fe fe-shield'],
            // ['name' =>'fe fe-shield-off'],
            // ['name' =>'fe fe-shopping-bag'],
            // ['name' =>'fe fe-shopping-cart'],
            // ['name' =>'fe fe-shuffle'],
            // ['name' =>'fe fe-sidebar'],
            // ['name' =>'fe fe-skip-back'],
            // ['name' =>'fe fe-skip-forward'],
            // ['name' =>'fe fe-slack'],
            // ['name' =>'fe fe-slash'],
            // ['name' =>'fe fe-sliders'],
            // ['name' =>'fe fe-smartphone'],
            // ['name' =>'fe fe-speaker'],
            // ['name' =>'fe fe-square'],
            // ['name' =>'fe fe-star'],
            // ['name' =>'fe fe-stop-circle'],
            // ['name' =>'fe fe-sun'],
            // ['name' =>'fe fe-sunrise'],
            // ['name' =>'fe fe-sunset'],
            // ['name' =>'fe fe-tablet'],
            // ['name' =>'fe fe-tag'],
            // ['name' =>'fe fe-target'],
            // ['name' =>'fe fe-terminal'],
            // ['name' =>'fe fe-thermometer'],
            // ['name' =>'fe fe-thumbs-down'],
            // ['name' =>'fe fe-thumbs-up'],
            // ['name' =>'fe fe-toggle-left'],
            // ['name' =>'fe fe-toggle-right'],
            // ['name' =>'fe fe-trash'],
            // ['name' =>'fe fe-trash-2'],
            // ['name' =>'fe fe-trending-down'],
            // ['name' =>'fe fe-trending-up'],
            // ['name' =>'fe fe-triangle'],
            // ['name' =>'fe fe-truck'],
            // ['name' =>'fe fe-tvli'],
            // ['name' =>'fe fe-twitter'],
            // ['name' =>' fe fe-type'],
            // ['name' =>'fe fe-umbrella'],
            // ['name' =>'fe fe-underline'],
            // ['name' =>'fe fe-unlock'],
            // ['name' =>'fe fe-upload'],
            // ['name' =>'fe fe-upload-cloud'],
            // ['name' =>'fe fe-user'],
            // ['name' =>'fe fe-user-check'],
            // ['name' =>'fe fe-user-minus'],
            // ['name' =>'fe fe-user-plus'],
            // ['name' =>'fe fe-user-x'],
            // ['name' =>'fe fe-users'],
            // ['name' =>' fe fe-video'],
            // ['name' =>'fe fe-video-off'],
            // ['name' =>'fe fe-voicemail'],
            // ['name' =>'fe fe-volume'],
            // ['name' =>'fe fe-volume-1'],
            // ['name' =>'fe fe-volume-2'],
            // ['name' =>'fe fe-volume-x'],
            // ['name' =>'fe fe-watch'],
            // ['name' =>'fe fe-wifi'],
            // ['name' =>'fe fe-wifi-off'],
            // ['name' =>'fe fe-wind'],
            // ['name' =>'fe fe-xi'],
            // ['name' =>'fe fe-x-circle'],
            // ['name' =>'fe fe-x-square'],
            // ['name' =>'fe fe-zapfe fe-zap-off'],
            // ['name' =>'fe fe-zoom-in'],
            // ['name' =>'fe fe-zoom-out'],
            ['name' => 'fa-500px', 'cheatsheet' => 'f26e;'],
            ['name' => 'fa-address-book', 'cheatsheet' => 'f2b9;'],
            ['name' => 'fa-address-book-o', 'cheatsheet' => 'f2ba;'],
            ['name' => 'fa-address-card', 'cheatsheet' => 'f2bb;'],
            ['name' => 'fa-address-card-o', 'cheatsheet' => 'f2bc;'],
            ['name' => 'fa-adjust', 'cheatsheet' => 'f042;'],
            ['name' => 'fa-adn', 'cheatsheet' => 'f170;'],
            ['name' => 'fa-align-center', 'cheatsheet' => 'f037;'],
            ['name' => 'fa-align-justify', 'cheatsheet' => 'f039;'],
            ['name' => 'fa-align-left', 'cheatsheet' => 'f036;'],
            ['name' => 'fa-align-right', 'cheatsheet' => 'f038;'],
            ['name' => 'fa-amazon', 'cheatsheet' => 'f270;'],
            ['name' => 'fa-ambulance', 'cheatsheet' => 'f0f9;'],
            ['name' => 'fa-american-sign-language-interpreting', 'cheatsheet' => 'f2a3;'],
            ['name' => 'fa-anchor', 'cheatsheet' => 'f13d;'],
            ['name' => 'fa-android', 'cheatsheet' => 'f17b;'],
            ['name' => 'fa-angellist', 'cheatsheet' => 'f209;'],
            ['name' => 'fa-angle-double-down', 'cheatsheet' => 'f103;'],
            ['name' => 'fa-angle-double-left', 'cheatsheet' => 'f100;'],
            ['name' => 'fa-angle-double-right', 'cheatsheet' => 'f101;'],
            ['name' => 'fa-angle-double-up', 'cheatsheet' => 'f102;'],
            ['name' => 'fa-angle-down', 'cheatsheet' => 'f107;'],
            ['name' => 'fa-angle-left', 'cheatsheet' => 'f104;'],
            ['name' => 'fa-angle-right', 'cheatsheet' => 'f105;'],
            ['name' => 'fa-angle-up', 'cheatsheet' => 'f106;'],
            ['name' => 'fa-apple', 'cheatsheet' => 'f179;'],
            ['name' => 'fa-archive', 'cheatsheet' => 'f187;'],
            ['name' => 'fa-area-chart', 'cheatsheet' => 'f1fe;'],
            ['name' => 'fa-arrow-circle-down', 'cheatsheet' => 'f0ab;'],
            ['name' => 'fa-arrow-circle-left', 'cheatsheet' => 'f0a8;'],
            ['name' => 'fa-arrow-circle-o-down', 'cheatsheet' => 'f01a;'],
            ['name' => 'fa-arrow-circle-o-left', 'cheatsheet' => 'f190;'],
            ['name' => 'fa-arrow-circle-o-right', 'cheatsheet' => 'f18e;'],
            ['name' => 'fa-arrow-circle-o-up', 'cheatsheet' => 'f01b;'],
            ['name' => 'fa-arrow-circle-right', 'cheatsheet' => 'f0a9;'],
            ['name' => 'fa-arrow-circle-up', 'cheatsheet' => 'f0aa;'],
            ['name' => 'fa-arrow-down', 'cheatsheet' => 'f063;'],
            ['name' => 'fa-arrow-left', 'cheatsheet' => 'f060;'],
            ['name' => 'fa-arrow-right', 'cheatsheet' => 'f061;'],
            ['name' => 'fa-arrow-up', 'cheatsheet' => 'f062;'],
            ['name' => 'fa-arrows', 'cheatsheet' => 'f047;'],
            ['name' => 'fa-arrows-alt', 'cheatsheet' => 'f0b2;'],
            ['name' => 'fa-arrows-h', 'cheatsheet' => 'f07e;'],
            ['name' => 'fa-arrows-v', 'cheatsheet' => 'f07d;'],
            ['name' => 'fa-asl-interpreting', 'cheatsheet' => 'f2a3;'],
            ['name' => 'fa-assistive-listening-systems', 'cheatsheet' => 'f2a2;'],
            ['name' => 'fa-asterisk', 'cheatsheet' => 'f069;'],
            ['name' => 'fa-at', 'cheatsheet' => 'f1fa;'],
            ['name' => 'fa-audio-description', 'cheatsheet' => 'f29e;'],
            ['name' => 'fa-automobile', 'cheatsheet' => 'f1b9;'],
            ['name' => 'fa-backward', 'cheatsheet' => 'f04a;'],
            ['name' => 'fa-balance-scale', 'cheatsheet' => 'f24e;'],
            ['name' => 'fa-ban', 'cheatsheet' => 'f05e;'],
            ['name' => 'fa-bandcamp', 'cheatsheet' => 'f2d5;'],
            ['name' => 'fa-bank', 'cheatsheet' => 'f19c;'],
            ['name' => 'fa-bar-chart', 'cheatsheet' => 'f080;'],
            ['name' => 'fa-bar-chart-o', 'cheatsheet' => 'f080;'],
            ['name' => 'fa-barcode', 'cheatsheet' => 'f02a;'],
            ['name' => 'fa-bars', 'cheatsheet' => 'f0c9;'],
            ['name' => 'fa-bath', 'cheatsheet' => 'f2cd;'],
            ['name' => 'fa-bathtub', 'cheatsheet' => 'f2cd;'],
            ['name' => 'fa-battery', 'cheatsheet' => 'f240;'],
            ['name' => 'fa-battery-0', 'cheatsheet' => 'f244;'],
            ['name' => 'fa-battery-1', 'cheatsheet' => 'f243;'],
            ['name' => 'fa-battery-2', 'cheatsheet' => 'f242;'],
            ['name' => 'fa-battery-3', 'cheatsheet' => 'f241;'],
            ['name' => 'fa-battery-4', 'cheatsheet' => 'f240;'],
            ['name' => 'fa-battery-empty', 'cheatsheet' => 'f244;'],
            ['name' => 'fa-battery-full', 'cheatsheet' => 'f240;'],
            ['name' => 'fa-battery-half', 'cheatsheet' => 'f242;'],
            ['name' => 'fa-battery-quarter', 'cheatsheet' => 'f243;'],
            ['name' => 'fa-battery-three-quarters', 'cheatsheet' => 'f241;'],
            ['name' => 'fa-bed', 'cheatsheet' => 'f236;'],
            ['name' => 'fa-beer', 'cheatsheet' => 'f0fc;'],
            ['name' => 'fa-behance', 'cheatsheet' => 'f1b4;'],
            ['name' => 'fa-behance-square', 'cheatsheet' => 'f1b5;'],
            ['name' => 'fa-bell', 'cheatsheet' => 'f0f3;'],
            ['name' => 'fa-bell-o', 'cheatsheet' => 'f0a2;'],
            ['name' => 'fa-bell-slash', 'cheatsheet' => 'f1f6;'],
            ['name' => 'fa-bell-slash-o', 'cheatsheet' => 'f1f7;'],
            ['name' => 'fa-bicycle', 'cheatsheet' => 'f206;'],
            ['name' => 'fa-binoculars', 'cheatsheet' => 'f1e5;'],
            ['name' => 'fa-birthday-cake', 'cheatsheet' => 'f1fd;'],
            ['name' => 'fa-bitbucket', 'cheatsheet' => 'f171;'],
            ['name' => 'fa-bitbucket-square', 'cheatsheet' => 'f172;'],
            ['name' => 'fa-bitcoin', 'cheatsheet' => 'f15a;'],
            ['name' => 'fa-black-tie', 'cheatsheet' => 'f27e;'],
            ['name' => 'fa-blind', 'cheatsheet' => 'f29d;'],
            ['name' => 'fa-bluetooth', 'cheatsheet' => 'f293;'],
            ['name' => 'fa-bluetooth-b', 'cheatsheet' => 'f294;'],
            ['name' => 'fa-bold', 'cheatsheet' => 'f032;'],
            ['name' => 'fa-bolt', 'cheatsheet' => 'f0e7;'],
            ['name' => 'fa-bomb', 'cheatsheet' => 'f1e2;'],
            ['name' => 'fa-book', 'cheatsheet' => 'f02d;'],
            ['name' => 'fa-bookmark', 'cheatsheet' => 'f02e;'],
            ['name' => 'fa-bookmark-o', 'cheatsheet' => 'f097;'],
            ['name' => 'fa-braille', 'cheatsheet' => 'f2a1;'],
            ['name' => 'fa-briefcase', 'cheatsheet' => 'f0b1;'],
            ['name' => 'fa-btc', 'cheatsheet' => 'f15a;'],
            ['name' => 'fa-bug', 'cheatsheet' => 'f188;'],
            ['name' => 'fa-building', 'cheatsheet' => 'f1ad;'],
            ['name' => 'fa-building-o', 'cheatsheet' => 'f0f7;'],
            ['name' => 'fa-bullhorn', 'cheatsheet' => 'f0a1;'],
            ['name' => 'fa-bullseye', 'cheatsheet' => 'f140;'],
            ['name' => 'fa-bus', 'cheatsheet' => 'f207;'],
            ['name' => 'fa-buysellads', 'cheatsheet' => 'f20d;'],
            ['name' => 'fa-cab', 'cheatsheet' => 'f1ba;'],
            ['name' => 'fa-calculator', 'cheatsheet' => 'f1ec;'],
            ['name' => 'fa-calendar', 'cheatsheet' => 'f073;'],
            ['name' => 'fa-calendar-check-o', 'cheatsheet' => 'f274;'],
            ['name' => 'fa-calendar-minus-o', 'cheatsheet' => 'f272;'],
            ['name' => 'fa-calendar-o', 'cheatsheet' => 'f133;'],
            ['name' => 'fa-calendar-plus-o', 'cheatsheet' => 'f271;'],
            ['name' => 'fa-calendar-times-o', 'cheatsheet' => 'f273;'],
            ['name' => 'fa-camera', 'cheatsheet' => 'f030;'],
            ['name' => 'fa-camera-retro', 'cheatsheet' => 'f083;'],
            ['name' => 'fa-car', 'cheatsheet' => 'f1b9;'],
            ['name' => 'fa-caret-down', 'cheatsheet' => 'f0d7;'],
            ['name' => 'fa-caret-left', 'cheatsheet' => 'f0d9;'],
            ['name' => 'fa-caret-right', 'cheatsheet' => 'f0da;'],
            ['name' => 'fa-caret-square-o-down', 'cheatsheet' => 'f150;'],
            ['name' => 'fa-caret-square-o-left', 'cheatsheet' => 'f191;'],
            ['name' => 'fa-caret-square-o-right', 'cheatsheet' => 'f152;'],
            ['name' => 'fa-caret-square-o-up', 'cheatsheet' => 'f151;'],
            ['name' => 'fa-caret-up', 'cheatsheet' => 'f0d8;'],
            ['name' => 'fa-cart-arrow-down', 'cheatsheet' => 'f218;'],
            ['name' => 'fa-cart-plus', 'cheatsheet' => 'f217;'],
            ['name' => 'fa-cc', 'cheatsheet' => 'f20a;'],
            ['name' => 'fa-cc-amex', 'cheatsheet' => 'f1f3;'],
            ['name' => 'fa-cc-diners-club', 'cheatsheet' => 'f24c;'],
            ['name' => 'fa-cc-discover', 'cheatsheet' => 'f1f2;'],
            ['name' => 'fa-cc-jcb', 'cheatsheet' => 'f24b;'],
            ['name' => 'fa-cc-mastercard', 'cheatsheet' => 'f1f1;'],
            ['name' => 'fa-cc-paypal', 'cheatsheet' => 'f1f4;'],
            ['name' => 'fa-cc-stripe', 'cheatsheet' => 'f1f5;'],
            ['name' => 'fa-cc-visa', 'cheatsheet' => 'f1f0;'],
            ['name' => 'fa-certificate', 'cheatsheet' => 'f0a3;'],
            ['name' => 'fa-chain', 'cheatsheet' => 'f0c1;'],
            ['name' => 'fa-chain-broken', 'cheatsheet' => 'f127;'],
            ['name' => 'fa-check', 'cheatsheet' => 'f00c;'],
            ['name' => 'fa-check-circle', 'cheatsheet' => 'f058;'],
            ['name' => 'fa-check-circle-o', 'cheatsheet' => 'f05d;'],
            ['name' => 'fa-check-square', 'cheatsheet' => 'f14a;'],
            ['name' => 'fa-check-square-o', 'cheatsheet' => 'f046;'],
            ['name' => 'fa-chevron-circle-down', 'cheatsheet' => 'f13a;'],
            ['name' => 'fa-chevron-circle-left', 'cheatsheet' => 'f137;'],
            ['name' => 'fa-chevron-circle-right', 'cheatsheet' => 'f138;'],
            ['name' => 'fa-chevron-circle-up', 'cheatsheet' => 'f139;'],
            ['name' => 'fa-chevron-down', 'cheatsheet' => 'f078;'],
            ['name' => 'fa-chevron-left', 'cheatsheet' => 'f053;'],
            ['name' => 'fa-chevron-right', 'cheatsheet' => 'f054;'],
            ['name' => 'fa-chevron-up', 'cheatsheet' => 'f077;'],
            ['name' => 'fa-child', 'cheatsheet' => 'f1ae;'],
            ['name' => 'fa-chrome', 'cheatsheet' => 'f268;'],
            ['name' => 'fa-circle', 'cheatsheet' => 'f111;'],
            ['name' => 'fa-circle-o', 'cheatsheet' => 'f10c;'],
            ['name' => 'fa-circle-o-notch', 'cheatsheet' => 'f1ce;'],
            ['name' => 'fa-circle-thin', 'cheatsheet' => 'f1db;'],
            ['name' => 'fa-clipboard', 'cheatsheet' => 'f0ea;'],
            ['name' => 'fa-clock-o', 'cheatsheet' => 'f017;'],
            ['name' => 'fa-clone', 'cheatsheet' => 'f24d;'],
            ['name' => 'fa-close', 'cheatsheet' => 'f00d;'],
            ['name' => 'fa-cloud', 'cheatsheet' => 'f0c2;'],
            ['name' => 'fa-cloud-download', 'cheatsheet' => 'f0ed;'],
            ['name' => 'fa-cloud-upload', 'cheatsheet' => 'f0ee;'],
            ['name' => 'fa-cny', 'cheatsheet' => 'f157;'],
            ['name' => 'fa-code', 'cheatsheet' => 'f121;'],
            ['name' => 'fa-code-fork', 'cheatsheet' => 'f126;'],
            ['name' => 'fa-codepen', 'cheatsheet' => 'f1cb;'],
            ['name' => 'fa-codiepie', 'cheatsheet' => 'f284;'],
            ['name' => 'fa-coffee', 'cheatsheet' => 'f0f4;'],
            ['name' => 'fa-cog', 'cheatsheet' => 'f013;'],
            ['name' => 'fa-cogs', 'cheatsheet' => 'f085;'],
            ['name' => 'fa-columns', 'cheatsheet' => 'f0db;'],
            ['name' => 'fa-comment', 'cheatsheet' => 'f075;'],
            ['name' => 'fa-comment-o', 'cheatsheet' => 'f0e5;'],
            ['name' => 'fa-commenting', 'cheatsheet' => 'f27a;'],
            ['name' => 'fa-commenting-o', 'cheatsheet' => 'f27b;'],
            ['name' => 'fa-comments', 'cheatsheet' => 'f086;'],
            ['name' => 'fa-comments-o', 'cheatsheet' => 'f0e6;'],
            ['name' => 'fa-compass', 'cheatsheet' => 'f14e;'],
            ['name' => 'fa-compress', 'cheatsheet' => 'f066;'],
            ['name' => 'fa-connectdevelop', 'cheatsheet' => 'f20e;'],
            ['name' => 'fa-contao', 'cheatsheet' => 'f26d;'],
            ['name' => 'fa-copy', 'cheatsheet' => 'f0c5;'],
            ['name' => 'fa-copyright', 'cheatsheet' => 'f1f9;'],
            ['name' => 'fa-creative-commons', 'cheatsheet' => 'f25e;'],
            ['name' => 'fa-credit-card', 'cheatsheet' => 'f09d;'],
            ['name' => 'fa-credit-card-alt', 'cheatsheet' => 'f283;'],
            ['name' => 'fa-crop', 'cheatsheet' => 'f125;'],
            ['name' => 'fa-crosshairs', 'cheatsheet' => 'f05b;'],
            ['name' => 'fa-css3', 'cheatsheet' => 'f13c;'],
            ['name' => 'fa-cube', 'cheatsheet' => 'f1b2;'],
            ['name' => 'fa-cubes', 'cheatsheet' => 'f1b3;'],
            ['name' => 'fa-cut', 'cheatsheet' => 'f0c4;'],
            ['name' => 'fa-cutlery', 'cheatsheet' => 'f0f5;'],
            ['name' => 'fa-dashboard', 'cheatsheet' => 'f0e4;'],
            ['name' => 'fa-dashcube', 'cheatsheet' => 'f210;'],
            ['name' => 'fa-database', 'cheatsheet' => 'f1c0;'],
            ['name' => 'fa-deaf', 'cheatsheet' => 'f2a4;'],
            ['name' => 'fa-deafness', 'cheatsheet' => 'f2a4;'],
            ['name' => 'fa-dedent', 'cheatsheet' => 'f03b;'],
            ['name' => 'fa-delicious', 'cheatsheet' => 'f1a5;'],
            ['name' => 'fa-desktop', 'cheatsheet' => 'f108;'],
            ['name' => 'fa-deviantart', 'cheatsheet' => 'f1bd;'],
            ['name' => 'fa-diamond', 'cheatsheet' => 'f219;'],
            ['name' => 'fa-digg', 'cheatsheet' => 'f1a6;'],
            ['name' => 'fa-dollar', 'cheatsheet' => 'f155;'],
            ['name' => 'fa-dot-circle-o', 'cheatsheet' => 'f192;'],
            ['name' => 'fa-download', 'cheatsheet' => 'f019;'],
            ['name' => 'fa-dribbble', 'cheatsheet' => 'f17d;'],
            ['name' => 'fa-drivers-license', 'cheatsheet' => 'f2c2;'],
            ['name' => 'fa-drivers-license-o', 'cheatsheet' => 'f2c3;'],
            ['name' => 'fa-dropbox', 'cheatsheet' => 'f16b;'],
            ['name' => 'fa-drupal', 'cheatsheet' => 'f1a9;'],
            ['name' => 'fa-edge', 'cheatsheet' => 'f282;'],
            ['name' => 'fa-edit', 'cheatsheet' => 'f044;'],
            ['name' => 'fa-eercast', 'cheatsheet' => 'f2da;'],
            ['name' => 'fa-eject', 'cheatsheet' => 'f052;'],
            ['name' => 'fa-ellipsis-h', 'cheatsheet' => 'f141;'],
            ['name' => 'fa-ellipsis-v', 'cheatsheet' => 'f142;'],
            ['name' => 'fa-empire', 'cheatsheet' => 'f1d1;'],
            ['name' => 'fa-envelope', 'cheatsheet' => 'f0e0;'],
            ['name' => 'fa-envelope-o', 'cheatsheet' => 'f003;'],
            ['name' => 'fa-envelope-open', 'cheatsheet' => 'f2b6;'],
            ['name' => 'fa-envelope-open-o', 'cheatsheet' => 'f2b7;'],
            ['name' => 'fa-envelope-square', 'cheatsheet' => 'f199;'],
            ['name' => 'fa-envira', 'cheatsheet' => 'f299;'],
            ['name' => 'fa-eraser', 'cheatsheet' => 'f12d;'],
            ['name' => 'fa-etsy', 'cheatsheet' => 'f2d7;'],
            ['name' => 'fa-eur', 'cheatsheet' => 'f153;'],
            ['name' => 'fa-euro', 'cheatsheet' => 'f153;'],
            ['name' => 'fa-exchange', 'cheatsheet' => 'f0ec;'],
            ['name' => 'fa-exclamation', 'cheatsheet' => 'f12a;'],
            ['name' => 'fa-exclamation-circle', 'cheatsheet' => 'f06a;'],
            ['name' => 'fa-exclamation-triangle', 'cheatsheet' => 'f071;'],
            ['name' => 'fa-expand', 'cheatsheet' => 'f065;'],
            ['name' => 'fa-expeditedssl', 'cheatsheet' => 'f23e;'],
            ['name' => 'fa-external-link', 'cheatsheet' => 'f08e;'],
            ['name' => 'fa-external-link-square', 'cheatsheet' => 'f14c;'],
            ['name' => 'fa-eye', 'cheatsheet' => 'f06e;'],
            ['name' => 'fa-eye-slash', 'cheatsheet' => 'f070;'],
            ['name' => 'fa-eyedropper', 'cheatsheet' => 'f1fb;'],
            ['name' => 'fa-fa', 'cheatsheet' => 'f2b4;'],
            ['name' => 'fa-facebook', 'cheatsheet' => 'f09a;'],
            ['name' => 'fa-facebook-f', 'cheatsheet' => 'f09a;'],
            ['name' => 'fa-facebook-official', 'cheatsheet' => 'f230;'],
            ['name' => 'fa-facebook-square', 'cheatsheet' => 'f082;'],
            ['name' => 'fa-fast-backward', 'cheatsheet' => 'f049;'],
            ['name' => 'fa-fast-forward', 'cheatsheet' => 'f050;'],
            ['name' => 'fa-fax', 'cheatsheet' => 'f1ac;'],
            ['name' => 'fa-feed', 'cheatsheet' => 'f09e;'],
            ['name' => 'fa-female', 'cheatsheet' => 'f182;'],
            ['name' => 'fa-fighter-jet', 'cheatsheet' => 'f0fb;'],
            ['name' => 'fa-file', 'cheatsheet' => 'f15b;'],
            ['name' => 'fa-file-archive-o', 'cheatsheet' => 'f1c6;'],
            ['name' => 'fa-file-audio-o', 'cheatsheet' => 'f1c7;'],
            ['name' => 'fa-file-code-o', 'cheatsheet' => 'f1c9;'],
            ['name' => 'fa-file-excel-o', 'cheatsheet' => 'f1c3;'],
            ['name' => 'fa-file-image-o', 'cheatsheet' => 'f1c5;'],
            ['name' => 'fa-file-movie-o', 'cheatsheet' => 'f1c8;'],
            ['name' => 'fa-file-o', 'cheatsheet' => 'f016;'],
            ['name' => 'fa-file-pdf-o', 'cheatsheet' => 'f1c1;'],
            ['name' => 'fa-file-photo-o', 'cheatsheet' => 'f1c5;'],
            ['name' => 'fa-file-picture-o', 'cheatsheet' => 'f1c5;'],
            ['name' => 'fa-file-powerpoint-o', 'cheatsheet' => 'f1c4;'],
            ['name' => 'fa-file-sound-o', 'cheatsheet' => 'f1c7;'],
            ['name' => 'fa-file-text', 'cheatsheet' => 'f15c;'],
            ['name' => 'fa-file-text-o', 'cheatsheet' => 'f0f6;'],
            ['name' => 'fa-file-video-o', 'cheatsheet' => 'f1c8;'],
            ['name' => 'fa-file-word-o', 'cheatsheet' => 'f1c2;'],
            ['name' => 'fa-file-zip-o', 'cheatsheet' => 'f1c6;'],
            ['name' => 'fa-files-o', 'cheatsheet' => 'f0c5;'],
            ['name' => 'fa-film', 'cheatsheet' => 'f008;'],
            ['name' => 'fa-filter', 'cheatsheet' => 'f0b0;'],
            ['name' => 'fa-fire', 'cheatsheet' => 'f06d;'],
            ['name' => 'fa-fire-extinguisher', 'cheatsheet' => 'f134;'],
            ['name' => 'fa-firefox', 'cheatsheet' => 'f269;'],
            ['name' => 'fa-first-order', 'cheatsheet' => 'f2b0;'],
            ['name' => 'fa-flag', 'cheatsheet' => 'f024;'],
            ['name' => 'fa-flag-checkered', 'cheatsheet' => 'f11e;'],
            ['name' => 'fa-flag-o', 'cheatsheet' => 'f11d;'],
            ['name' => 'fa-flash', 'cheatsheet' => 'f0e7;'],
            ['name' => 'fa-flask', 'cheatsheet' => 'f0c3;'],
            ['name' => 'fa-flickr', 'cheatsheet' => 'f16e;'],
            ['name' => 'fa-floppy-o', 'cheatsheet' => 'f0c7;'],
            ['name' => 'fa-folder', 'cheatsheet' => 'f07b;'],
            ['name' => 'fa-folder-o', 'cheatsheet' => 'f114;'],
            ['name' => 'fa-folder-open', 'cheatsheet' => 'f07c;'],
            ['name' => 'fa-folder-open-o', 'cheatsheet' => 'f115;'],
            ['name' => 'fa-font', 'cheatsheet' => 'f031;'],
            ['name' => 'fa-font-awesome', 'cheatsheet' => 'f2b4;'],
            ['name' => 'fa-fonticons', 'cheatsheet' => 'f280;'],
            ['name' => 'fa-fort-awesome', 'cheatsheet' => 'f286;'],
            ['name' => 'fa-forumbee', 'cheatsheet' => 'f211;'],
            ['name' => 'fa-forward', 'cheatsheet' => 'f04e;'],
            ['name' => 'fa-foursquare', 'cheatsheet' => 'f180;'],
            ['name' => 'fa-free-code-camp', 'cheatsheet' => 'f2c5;'],
            ['name' => 'fa-frown-o', 'cheatsheet' => 'f119;'],
            ['name' => 'fa-futbol-o', 'cheatsheet' => 'f1e3;'],
            ['name' => 'fa-gamepad', 'cheatsheet' => 'f11b;'],
            ['name' => 'fa-gavel', 'cheatsheet' => 'f0e3;'],
            ['name' => 'fa-gbp', 'cheatsheet' => 'f154;'],
            ['name' => 'fa-ge', 'cheatsheet' => 'f1d1;'],
            ['name' => 'fa-gear', 'cheatsheet' => 'f013;'],
            ['name' => 'fa-gears', 'cheatsheet' => 'f085;'],
            ['name' => 'fa-genderless', 'cheatsheet' => 'f22d;'],
            ['name' => 'fa-get-pocket', 'cheatsheet' => 'f265;'],
            ['name' => 'fa-gg', 'cheatsheet' => 'f260;'],
            ['name' => 'fa-gg-circle', 'cheatsheet' => 'f261;'],
            ['name' => 'fa-gift', 'cheatsheet' => 'f06b;'],
            ['name' => 'fa-git', 'cheatsheet' => 'f1d3;'],
            ['name' => 'fa-git-square', 'cheatsheet' => 'f1d2;'],
            ['name' => 'fa-github', 'cheatsheet' => 'f09b;'],
            ['name' => 'fa-github-alt', 'cheatsheet' => 'f113;'],
            ['name' => 'fa-github-square', 'cheatsheet' => 'f092;'],
            ['name' => 'fa-gitlab', 'cheatsheet' => 'f296;'],
            ['name' => 'fa-gittip', 'cheatsheet' => 'f184;'],
            ['name' => 'fa-glass', 'cheatsheet' => 'f000;'],
            ['name' => 'fa-glide', 'cheatsheet' => 'f2a5;'],
            ['name' => 'fa-glide-g', 'cheatsheet' => 'f2a6;'],
            ['name' => 'fa-globe', 'cheatsheet' => 'f0ac;'],
            ['name' => 'fa-google', 'cheatsheet' => 'f1a0;'],
            ['name' => 'fa-google-plus', 'cheatsheet' => 'f0d5;'],
            ['name' => 'fa-google-plus-circle', 'cheatsheet' => 'f2b3;'],
            ['name' => 'fa-google-plus-official', 'cheatsheet' => 'f2b3;'],
            ['name' => 'fa-google-plus-square', 'cheatsheet' => 'f0d4;'],
            ['name' => 'fa-google-wallet', 'cheatsheet' => 'f1ee;'],
            ['name' => 'fa-graduation-cap', 'cheatsheet' => 'f19d;'],
            ['name' => 'fa-gratipay', 'cheatsheet' => 'f184;'],
            ['name' => 'fa-grav', 'cheatsheet' => 'f2d6;'],
            ['name' => 'fa-group', 'cheatsheet' => 'f0c0;'],
            ['name' => 'fa-h-square', 'cheatsheet' => 'f0fd;'],
            ['name' => 'fa-hacker-news', 'cheatsheet' => 'f1d4;'],
            ['name' => 'fa-hand-grab-o', 'cheatsheet' => 'f255;'],
            ['name' => 'fa-hand-lizard-o', 'cheatsheet' => 'f258;'],
            ['name' => 'fa-hand-o-down', 'cheatsheet' => 'f0a7;'],
            ['name' => 'fa-hand-o-left', 'cheatsheet' => 'f0a5;'],
            ['name' => 'fa-hand-o-right', 'cheatsheet' => 'f0a4;'],
            ['name' => 'fa-hand-o-up', 'cheatsheet' => 'f0a6;'],
            ['name' => 'fa-hand-paper-o', 'cheatsheet' => 'f256;'],
            ['name' => 'fa-hand-peace-o', 'cheatsheet' => 'f25b;'],
            ['name' => 'fa-hand-pointer-o', 'cheatsheet' => 'f25a;'],
            ['name' => 'fa-hand-rock-o', 'cheatsheet' => 'f255;'],
            ['name' => 'fa-hand-scissors-o', 'cheatsheet' => 'f257;'],
            ['name' => 'fa-hand-spock-o', 'cheatsheet' => 'f259;'],
            ['name' => 'fa-hand-stop-o', 'cheatsheet' => 'f256;'],
            ['name' => 'fa-handshake-o', 'cheatsheet' => 'f2b5;'],
            ['name' => 'fa-hard-of-hearing', 'cheatsheet' => 'f2a4;'],
            ['name' => 'fa-hashtag', 'cheatsheet' => 'f292;'],
            ['name' => 'fa-hdd-o', 'cheatsheet' => 'f0a0;'],
            ['name' => 'fa-header', 'cheatsheet' => 'f1dc;'],
            ['name' => 'fa-headphones', 'cheatsheet' => 'f025;'],
            ['name' => 'fa-heart', 'cheatsheet' => 'f004;'],
            ['name' => 'fa-heart-o', 'cheatsheet' => 'f08a;'],
            ['name' => 'fa-heartbeat', 'cheatsheet' => 'f21e;'],
            ['name' => 'fa-history', 'cheatsheet' => 'f1da;'],
            ['name' => 'fa-home', 'cheatsheet' => 'f015;'],
            ['name' => 'fa-hospital-o', 'cheatsheet' => 'f0f8;'],
            ['name' => 'fa-hotel', 'cheatsheet' => 'f236;'],
            ['name' => 'fa-hourglass', 'cheatsheet' => 'f254;'],
            ['name' => 'fa-hourglass-1', 'cheatsheet' => 'f251;'],
            ['name' => 'fa-hourglass-2', 'cheatsheet' => 'f252;'],
            ['name' => 'fa-hourglass-3', 'cheatsheet' => 'f253;'],
            ['name' => 'fa-hourglass-end', 'cheatsheet' => 'f253;'],
            ['name' => 'fa-hourglass-half', 'cheatsheet' => 'f252;'],
            ['name' => 'fa-hourglass-o', 'cheatsheet' => 'f250;'],
            ['name' => 'fa-hourglass-start', 'cheatsheet' => 'f251;'],
            ['name' => 'fa-houzz', 'cheatsheet' => 'f27c;'],
            ['name' => 'fa-html5', 'cheatsheet' => 'f13b;'],
            ['name' => 'fa-i-cursor', 'cheatsheet' => 'f246;'],
            ['name' => 'fa-id-badge', 'cheatsheet' => 'f2c1;'],
            ['name' => 'fa-id-card', 'cheatsheet' => 'f2c2;'],
            ['name' => 'fa-id-card-o', 'cheatsheet' => 'f2c3;'],
            ['name' => 'fa-ils', 'cheatsheet' => 'f20b;'],
            ['name' => 'fa-image', 'cheatsheet' => 'f03e;'],
            ['name' => 'fa-imdb', 'cheatsheet' => 'f2d8;'],
            ['name' => 'fa-inbox', 'cheatsheet' => 'f01c;'],
            ['name' => 'fa-indent', 'cheatsheet' => 'f03c;'],
            ['name' => 'fa-industry', 'cheatsheet' => 'f275;'],
            ['name' => 'fa-info', 'cheatsheet' => 'f129;'],
            ['name' => 'fa-info-circle', 'cheatsheet' => 'f05a;'],
            ['name' => 'fa-inr', 'cheatsheet' => 'f156;'],
            ['name' => 'fa-instagram', 'cheatsheet' => 'f16d;'],
            ['name' => 'fa-institution', 'cheatsheet' => 'f19c;'],
            ['name' => 'fa-internet-explorer', 'cheatsheet' => 'f26b;'],
            ['name' => 'fa-intersex', 'cheatsheet' => 'f224;'],
            ['name' => 'fa-ioxhost', 'cheatsheet' => 'f208;'],
            ['name' => 'fa-italic', 'cheatsheet' => 'f033;'],
            ['name' => 'fa-joomla', 'cheatsheet' => 'f1aa;'],
            ['name' => 'fa-jpy', 'cheatsheet' => 'f157;'],
            ['name' => 'fa-jsfiddle', 'cheatsheet' => 'f1cc;'],
            ['name' => 'fa-key', 'cheatsheet' => 'f084;'],
            ['name' => 'fa-keyboard-o', 'cheatsheet' => 'f11c;'],
            ['name' => 'fa-krw', 'cheatsheet' => 'f159;'],
            ['name' => 'fa-language', 'cheatsheet' => 'f1ab;'],
            ['name' => 'fa-laptop', 'cheatsheet' => 'f109;'],
            ['name' => 'fa-lastfm', 'cheatsheet' => 'f202;'],
            ['name' => 'fa-lastfm-square', 'cheatsheet' => 'f203;'],
            ['name' => 'fa-leaf', 'cheatsheet' => 'f06c;'],
            ['name' => 'fa-leanpub', 'cheatsheet' => 'f212;'],
            ['name' => 'fa-legal', 'cheatsheet' => 'f0e3;'],
            ['name' => 'fa-lemon-o', 'cheatsheet' => 'f094;'],
            ['name' => 'fa-level-down', 'cheatsheet' => 'f149;'],
            ['name' => 'fa-level-up', 'cheatsheet' => 'f148;'],
            ['name' => 'fa-life-bouy', 'cheatsheet' => 'f1cd;'],
            ['name' => 'fa-life-buoy', 'cheatsheet' => 'f1cd;'],
            ['name' => 'fa-life-ring', 'cheatsheet' => 'f1cd;'],
            ['name' => 'fa-life-saver', 'cheatsheet' => 'f1cd;'],
            ['name' => 'fa-lightbulb-o', 'cheatsheet' => 'f0eb;'],
            ['name' => 'fa-line-chart', 'cheatsheet' => 'f201;'],
            ['name' => 'fa-link', 'cheatsheet' => 'f0c1;'],
            ['name' => 'fa-linkedin', 'cheatsheet' => 'f0e1;'],
            ['name' => 'fa-linkedin-square', 'cheatsheet' => 'f08c;'],
            ['name' => 'fa-linode', 'cheatsheet' => 'f2b8;'],
            ['name' => 'fa-linux', 'cheatsheet' => 'f17c;'],
            ['name' => 'fa-list', 'cheatsheet' => 'f03a;'],
            ['name' => 'fa-list-alt', 'cheatsheet' => 'f022;'],
            ['name' => 'fa-list-ol', 'cheatsheet' => 'f0cb;'],
            ['name' => 'fa-list-ul', 'cheatsheet' => 'f0ca;'],
            ['name' => 'fa-location-arrow', 'cheatsheet' => 'f124;'],
            ['name' => 'fa-lock', 'cheatsheet' => 'f023;'],
            ['name' => 'fa-long-arrow-down', 'cheatsheet' => 'f175;'],
            ['name' => 'fa-long-arrow-left', 'cheatsheet' => 'f177;'],
            ['name' => 'fa-long-arrow-right', 'cheatsheet' => 'f178;'],
            ['name' => 'fa-long-arrow-up', 'cheatsheet' => 'f176;'],
            ['name' => 'fa-low-vision', 'cheatsheet' => 'f2a8;'],
            ['name' => 'fa-magic', 'cheatsheet' => 'f0d0;'],
            ['name' => 'fa-magnet', 'cheatsheet' => 'f076;'],
            ['name' => 'fa-mail-forward', 'cheatsheet' => 'f064;'],
            ['name' => 'fa-mail-reply', 'cheatsheet' => 'f112;'],
            ['name' => 'fa-mail-reply-all', 'cheatsheet' => 'f122;'],
            ['name' => 'fa-male', 'cheatsheet' => 'f183;'],
            ['name' => 'fa-map', 'cheatsheet' => 'f279;'],
            ['name' => 'fa-map-marker', 'cheatsheet' => 'f041;'],
            ['name' => 'fa-map-o', 'cheatsheet' => 'f278;'],
            ['name' => 'fa-map-pin', 'cheatsheet' => 'f276;'],
            ['name' => 'fa-map-signs', 'cheatsheet' => 'f277;'],
            ['name' => 'fa-mars', 'cheatsheet' => 'f222;'],
            ['name' => 'fa-mars-double', 'cheatsheet' => 'f227;'],
            ['name' => 'fa-mars-stroke', 'cheatsheet' => 'f229;'],
            ['name' => 'fa-mars-stroke-h', 'cheatsheet' => 'f22b;'],
            ['name' => 'fa-mars-stroke-v', 'cheatsheet' => 'f22a;'],
            ['name' => 'fa-maxcdn', 'cheatsheet' => 'f136;'],
            ['name' => 'fa-meanpath', 'cheatsheet' => 'f20c;'],
            ['name' => 'fa-medium', 'cheatsheet' => 'f23a;'],
            ['name' => 'fa-medkit', 'cheatsheet' => 'f0fa;'],
            ['name' => 'fa-meetup', 'cheatsheet' => 'f2e0;'],
            ['name' => 'fa-meh-o', 'cheatsheet' => 'f11a;'],
            ['name' => 'fa-mercury', 'cheatsheet' => 'f223;'],
            ['name' => 'fa-microchip', 'cheatsheet' => 'f2db;'],
            ['name' => 'fa-microphone', 'cheatsheet' => 'f130;'],
            ['name' => 'fa-microphone-slash', 'cheatsheet' => 'f131;'],
            ['name' => 'fa-minus', 'cheatsheet' => 'f068;'],
            ['name' => 'fa-minus-circle', 'cheatsheet' => 'f056;'],
            ['name' => 'fa-minus-square', 'cheatsheet' => 'f146;'],
            ['name' => 'fa-minus-square-o', 'cheatsheet' => 'f147;'],
            ['name' => 'fa-mixcloud', 'cheatsheet' => 'f289;'],
            ['name' => 'fa-mobile', 'cheatsheet' => 'f10b;'],
            ['name' => 'fa-mobile-phone', 'cheatsheet' => 'f10b;'],
            ['name' => 'fa-modx', 'cheatsheet' => 'f285;'],
            ['name' => 'fa-money', 'cheatsheet' => 'f0d6;'],
            ['name' => 'fa-moon-o', 'cheatsheet' => 'f186;'],
            ['name' => 'fa-mortar-board', 'cheatsheet' => 'f19d;'],
            ['name' => 'fa-motorcycle', 'cheatsheet' => 'f21c;'],
            ['name' => 'fa-mouse-pointer', 'cheatsheet' => 'f245;'],
            ['name' => 'fa-music', 'cheatsheet' => 'f001;'],
            ['name' => 'fa-navicon', 'cheatsheet' => 'f0c9;'],
            ['name' => 'fa-neuter', 'cheatsheet' => 'f22c;'],
            ['name' => 'fa-newspaper-o', 'cheatsheet' => 'f1ea;'],
            ['name' => 'fa-object-group', 'cheatsheet' => 'f247;'],
            ['name' => 'fa-object-ungroup', 'cheatsheet' => 'f248;'],
            ['name' => 'fa-odnoklassniki', 'cheatsheet' => 'f263;'],
            ['name' => 'fa-odnoklassniki-square', 'cheatsheet' => 'f264;'],
            ['name' => 'fa-opencart', 'cheatsheet' => 'f23d;'],
            ['name' => 'fa-openid', 'cheatsheet' => 'f19b;'],
            ['name' => 'fa-opera', 'cheatsheet' => 'f26a;'],
            ['name' => 'fa-optin-monster', 'cheatsheet' => 'f23c;'],
            ['name' => 'fa-outdent', 'cheatsheet' => 'f03b;'],
            ['name' => 'fa-pagelines', 'cheatsheet' => 'f18c;'],
            ['name' => 'fa-paint-brush', 'cheatsheet' => 'f1fc;'],
            ['name' => 'fa-paper-plane', 'cheatsheet' => 'f1d8;'],
            ['name' => 'fa-paper-plane-o', 'cheatsheet' => 'f1d9;'],
            ['name' => 'fa-paperclip', 'cheatsheet' => 'f0c6;'],
            ['name' => 'fa-paragraph', 'cheatsheet' => 'f1dd;'],
            ['name' => 'fa-paste', 'cheatsheet' => 'f0ea;'],
            ['name' => 'fa-pause', 'cheatsheet' => 'f04c;'],
            ['name' => 'fa-pause-circle', 'cheatsheet' => 'f28b;'],
            ['name' => 'fa-pause-circle-o', 'cheatsheet' => 'f28c;'],
            ['name' => 'fa-paw', 'cheatsheet' => 'f1b0;'],
            ['name' => 'fa-paypal', 'cheatsheet' => 'f1ed;'],
            ['name' => 'fa-pencil', 'cheatsheet' => 'f040;'],
            ['name' => 'fa-pencil-square', 'cheatsheet' => 'f14b;'],
            ['name' => 'fa-pencil-square-o', 'cheatsheet' => 'f044;'],
            ['name' => 'fa-percent', 'cheatsheet' => 'f295;'],
            ['name' => 'fa-phone', 'cheatsheet' => 'f095;'],
            ['name' => 'fa-phone-square', 'cheatsheet' => 'f098;'],
            ['name' => 'fa-photo', 'cheatsheet' => 'f03e;'],
            ['name' => 'fa-picture-o', 'cheatsheet' => 'f03e;'],
            ['name' => 'fa-pie-chart', 'cheatsheet' => 'f200;'],
            ['name' => 'fa-pied-piper', 'cheatsheet' => 'f2ae;'],
            ['name' => 'fa-pied-piper-alt', 'cheatsheet' => 'f1a8;'],
            ['name' => 'fa-pied-piper-pp', 'cheatsheet' => 'f1a7;'],
            ['name' => 'fa-pinterest', 'cheatsheet' => 'f0d2;'],
            ['name' => 'fa-pinterest-p', 'cheatsheet' => 'f231;'],
            ['name' => 'fa-pinterest-square', 'cheatsheet' => 'f0d3;'],
            ['name' => 'fa-plane', 'cheatsheet' => 'f072;'],
            ['name' => 'fa-play', 'cheatsheet' => 'f04b;'],
            ['name' => 'fa-play-circle', 'cheatsheet' => 'f144;'],
            ['name' => 'fa-play-circle-o', 'cheatsheet' => 'f01d;'],
            ['name' => 'fa-plug', 'cheatsheet' => 'f1e6;'],
            ['name' => 'fa-plus', 'cheatsheet' => 'f067;'],
            ['name' => 'fa-plus-circle', 'cheatsheet' => 'f055;'],
            ['name' => 'fa-plus-square', 'cheatsheet' => 'f0fe;'],
            ['name' => 'fa-plus-square-o', 'cheatsheet' => 'f196;'],
            ['name' => 'fa-podcast', 'cheatsheet' => 'f2ce;'],
            ['name' => 'fa-power-off', 'cheatsheet' => 'f011;'],
            ['name' => 'fa-print', 'cheatsheet' => 'f02f;'],
            ['name' => 'fa-product-hunt', 'cheatsheet' => 'f288;'],
            ['name' => 'fa-puzzle-piece', 'cheatsheet' => 'f12e;'],
            ['name' => 'fa-qq', 'cheatsheet' => 'f1d6;'],
            ['name' => 'fa-qrcode', 'cheatsheet' => 'f029;'],
            ['name' => 'fa-question', 'cheatsheet' => 'f128;'],
            ['name' => 'fa-question-circle', 'cheatsheet' => 'f059;'],
            ['name' => 'fa-question-circle-o', 'cheatsheet' => 'f29c;'],
            ['name' => 'fa-quora', 'cheatsheet' => 'f2c4;'],
            ['name' => 'fa-quote-left', 'cheatsheet' => 'f10d;'],
            ['name' => 'fa-quote-right', 'cheatsheet' => 'f10e;'],
            ['name' => 'fa-ra', 'cheatsheet' => 'f1d0;'],
            ['name' => 'fa-random', 'cheatsheet' => 'f074;'],
            ['name' => 'fa-ravelry', 'cheatsheet' => 'f2d9;'],
            ['name' => 'fa-rebel', 'cheatsheet' => 'f1d0;'],
            ['name' => 'fa-recycle', 'cheatsheet' => 'f1b8;'],
            ['name' => 'fa-reddit', 'cheatsheet' => 'f1a1;'],
            ['name' => 'fa-reddit-alien', 'cheatsheet' => 'f281;'],
            ['name' => 'fa-reddit-square', 'cheatsheet' => 'f1a2;'],
            ['name' => 'fa-refresh', 'cheatsheet' => 'f021;'],
            ['name' => 'fa-registered', 'cheatsheet' => 'f25d;'],
            ['name' => 'fa-remove', 'cheatsheet' => 'f00d;'],
            ['name' => 'fa-renren', 'cheatsheet' => 'f18b;'],
            ['name' => 'fa-reorder', 'cheatsheet' => 'f0c9;'],
            ['name' => 'fa-repeat', 'cheatsheet' => 'f01e;'],
            ['name' => 'fa-reply', 'cheatsheet' => 'f112;'],
            ['name' => 'fa-reply-all', 'cheatsheet' => 'f122;'],
            ['name' => 'fa-resistance', 'cheatsheet' => 'f1d0;'],
            ['name' => 'fa-retweet', 'cheatsheet' => 'f079;'],
            ['name' => 'fa-rmb', 'cheatsheet' => 'f157;'],
            ['name' => 'fa-road', 'cheatsheet' => 'f018;'],
            ['name' => 'fa-rocket', 'cheatsheet' => 'f135;'],
            ['name' => 'fa-rotate-left', 'cheatsheet' => 'f0e2;'],
            ['name' => 'fa-rotate-right', 'cheatsheet' => 'f01e;'],
            ['name' => 'fa-rouble', 'cheatsheet' => 'f158;'],
            ['name' => 'fa-rss', 'cheatsheet' => 'f09e;'],
            ['name' => 'fa-rss-square', 'cheatsheet' => 'f143;'],
            ['name' => 'fa-rub', 'cheatsheet' => 'f158;'],
            ['name' => 'fa-ruble', 'cheatsheet' => 'f158;'],
            ['name' => 'fa-rupee', 'cheatsheet' => 'f156;'],
            ['name' => 'fa-s15', 'cheatsheet' => 'f2cd;'],
            ['name' => 'fa-safari', 'cheatsheet' => 'f267;'],
            ['name' => 'fa-save', 'cheatsheet' => 'f0c7;'],
            ['name' => 'fa-scissors', 'cheatsheet' => 'f0c4;'],
            ['name' => 'fa-scribd', 'cheatsheet' => 'f28a;'],
            ['name' => 'fa-search', 'cheatsheet' => 'f002;'],
            ['name' => 'fa-search-minus', 'cheatsheet' => 'f010;'],
            ['name' => 'fa-search-plus', 'cheatsheet' => 'f00e;'],
            ['name' => 'fa-sellsy', 'cheatsheet' => 'f213;'],
            ['name' => 'fa-send', 'cheatsheet' => 'f1d8;'],
            ['name' => 'fa-send-o', 'cheatsheet' => 'f1d9;'],
            ['name' => 'fa-server', 'cheatsheet' => 'f233;'],
            ['name' => 'fa-share', 'cheatsheet' => 'f064;'],
            ['name' => 'fa-share-alt', 'cheatsheet' => 'f1e0;'],
            ['name' => 'fa-share-alt-square', 'cheatsheet' => 'f1e1;'],
            ['name' => 'fa-share-square', 'cheatsheet' => 'f14d;'],
            ['name' => 'fa-share-square-o', 'cheatsheet' => 'f045;'],
            ['name' => 'fa-shekel', 'cheatsheet' => 'f20b;'],
            ['name' => 'fa-sheqel', 'cheatsheet' => 'f20b;'],
            ['name' => 'fa-shield', 'cheatsheet' => 'f132;'],
            ['name' => 'fa-ship', 'cheatsheet' => 'f21a;'],
            ['name' => 'fa-shirtsinbulk', 'cheatsheet' => 'f214;'],
            ['name' => 'fa-shopping-bag', 'cheatsheet' => 'f290;'],
            ['name' => 'fa-shopping-basket', 'cheatsheet' => 'f291;'],
            ['name' => 'fa-shopping-cart', 'cheatsheet' => 'f07a;'],
            ['name' => 'fa-shower', 'cheatsheet' => 'f2cc;'],
            ['name' => 'fa-sign-in', 'cheatsheet' => 'f090;'],
            ['name' => 'fa-sign-language', 'cheatsheet' => 'f2a7;'],
            ['name' => 'fa-sign-out', 'cheatsheet' => 'f08b;'],
            ['name' => 'fa-signal', 'cheatsheet' => 'f012;'],
            ['name' => 'fa-signing', 'cheatsheet' => 'f2a7;'],
            ['name' => 'fa-simplybuilt', 'cheatsheet' => 'f215;'],
            ['name' => 'fa-sitemap', 'cheatsheet' => 'f0e8;'],
            ['name' => 'fa-skyatlas', 'cheatsheet' => 'f216;'],
            ['name' => 'fa-skype', 'cheatsheet' => 'f17e;'],
            ['name' => 'fa-slack', 'cheatsheet' => 'f198;'],
            ['name' => 'fa-sliders', 'cheatsheet' => 'f1de;'],
            ['name' => 'fa-slideshare', 'cheatsheet' => 'f1e7;'],
            ['name' => 'fa-smile-o', 'cheatsheet' => 'f118;'],
            ['name' => 'fa-snapchat', 'cheatsheet' => 'f2ab;'],
            ['name' => 'fa-snapchat-ghost', 'cheatsheet' => 'f2ac;'],
            ['name' => 'fa-snapchat-square', 'cheatsheet' => 'f2ad;'],
            ['name' => 'fa-snowflake-o', 'cheatsheet' => 'f2dc;'],
            ['name' => 'fa-soccer-ball-o', 'cheatsheet' => 'f1e3;'],
            ['name' => 'fa-sort', 'cheatsheet' => 'f0dc;'],
            ['name' => 'fa-sort-alpha-asc', 'cheatsheet' => 'f15d;'],
            ['name' => 'fa-sort-alpha-desc', 'cheatsheet' => 'f15e;'],
            ['name' => 'fa-sort-amount-asc', 'cheatsheet' => 'f160;'],
            ['name' => 'fa-sort-amount-desc', 'cheatsheet' => 'f161;'],
            ['name' => 'fa-sort-asc', 'cheatsheet' => 'f0de;'],
            ['name' => 'fa-sort-desc', 'cheatsheet' => 'f0dd;'],
            ['name' => 'fa-sort-down', 'cheatsheet' => 'f0dd;'],
            ['name' => 'fa-sort-numeric-asc', 'cheatsheet' => 'f162;'],
            ['name' => 'fa-sort-numeric-desc', 'cheatsheet' => 'f163;'],
            ['name' => 'fa-sort-up', 'cheatsheet' => 'f0de;'],
            ['name' => 'fa-soundcloud', 'cheatsheet' => 'f1be;'],
            ['name' => 'fa-space-shuttle', 'cheatsheet' => 'f197;'],
            ['name' => 'fa-spinner', 'cheatsheet' => 'f110;'],
            ['name' => 'fa-spoon', 'cheatsheet' => 'f1b1;'],
            ['name' => 'fa-spotify', 'cheatsheet' => 'f1bc;'],
            ['name' => 'fa-square', 'cheatsheet' => 'f0c8;'],
            ['name' => 'fa-square-o', 'cheatsheet' => 'f096;'],
            ['name' => 'fa-stack-exchange', 'cheatsheet' => 'f18d;'],
            ['name' => 'fa-stack-overflow', 'cheatsheet' => 'f16c;'],
            ['name' => 'fa-star', 'cheatsheet' => 'f005;'],
            ['name' => 'fa-star-half', 'cheatsheet' => 'f089;'],
            ['name' => 'fa-star-half-empty', 'cheatsheet' => 'f123;'],
            ['name' => 'fa-star-half-full', 'cheatsheet' => 'f123;'],
            ['name' => 'fa-star-half-o', 'cheatsheet' => 'f123;'],
            ['name' => 'fa-star-o', 'cheatsheet' => 'f006;'],
            ['name' => 'fa-steam', 'cheatsheet' => 'f1b6;'],
            ['name' => 'fa-steam-square', 'cheatsheet' => 'f1b7;'],
            ['name' => 'fa-step-backward', 'cheatsheet' => 'f048;'],
            ['name' => 'fa-step-forward', 'cheatsheet' => 'f051;'],
            ['name' => 'fa-stethoscope', 'cheatsheet' => 'f0f1;'],
            ['name' => 'fa-sticky-note', 'cheatsheet' => 'f249;'],
            ['name' => 'fa-sticky-note-o', 'cheatsheet' => 'f24a;'],
            ['name' => 'fa-stop', 'cheatsheet' => 'f04d;'],
            ['name' => 'fa-stop-circle', 'cheatsheet' => 'f28d;'],
            ['name' => 'fa-stop-circle-o', 'cheatsheet' => 'f28e;'],
            ['name' => 'fa-street-view', 'cheatsheet' => 'f21d;'],
            ['name' => 'fa-strikethrough', 'cheatsheet' => 'f0cc;'],
            ['name' => 'fa-stumbleupon', 'cheatsheet' => 'f1a4;'],
            ['name' => 'fa-stumbleupon-circle', 'cheatsheet' => 'f1a3;'],
            ['name' => 'fa-subscript', 'cheatsheet' => 'f12c;'],
            ['name' => 'fa-subway', 'cheatsheet' => 'f239;'],
            ['name' => 'fa-suitcase', 'cheatsheet' => 'f0f2;'],
            ['name' => 'fa-sun-o', 'cheatsheet' => 'f185;'],
            ['name' => 'fa-superpowers', 'cheatsheet' => 'f2dd;'],
            ['name' => 'fa-superscript', 'cheatsheet' => 'f12b;'],
            ['name' => 'fa-support', 'cheatsheet' => 'f1cd;'],
            ['name' => 'fa-table', 'cheatsheet' => 'f0ce;'],
            ['name' => 'fa-tablet', 'cheatsheet' => 'f10a;'],
            ['name' => 'fa-tachometer', 'cheatsheet' => 'f0e4;'],
            ['name' => 'fa-tag', 'cheatsheet' => 'f02b;'],
            ['name' => 'fa-tags', 'cheatsheet' => 'f02c;'],
            ['name' => 'fa-tasks', 'cheatsheet' => 'f0ae;'],
            ['name' => 'fa-taxi', 'cheatsheet' => 'f1ba;'],
            ['name' => 'fa-telegram', 'cheatsheet' => 'f2c6;'],
            ['name' => 'fa-television', 'cheatsheet' => 'f26c;'],
            ['name' => 'fa-tencent-weibo', 'cheatsheet' => 'f1d5;'],
            ['name' => 'fa-terminal', 'cheatsheet' => 'f120;'],
            ['name' => 'fa-text-height', 'cheatsheet' => 'f034;'],
            ['name' => 'fa-text-width', 'cheatsheet' => 'f035;'],
            ['name' => 'fa-th', 'cheatsheet' => 'f00a;'],
            ['name' => 'fa-th-large', 'cheatsheet' => 'f009;'],
            ['name' => 'fa-th-list', 'cheatsheet' => 'f00b;'],
            ['name' => 'fa-themeisle', 'cheatsheet' => 'f2b2;'],
            ['name' => 'fa-thermometer', 'cheatsheet' => 'f2c7;'],
            ['name' => 'fa-thermometer-0', 'cheatsheet' => 'f2cb;'],
            ['name' => 'fa-thermometer-1', 'cheatsheet' => 'f2ca;'],
            ['name' => 'fa-thermometer-2', 'cheatsheet' => 'f2c9;'],
            ['name' => 'fa-thermometer-3', 'cheatsheet' => 'f2c8;'],
            ['name' => 'fa-thermometer-4', 'cheatsheet' => 'f2c7;'],
            ['name' => 'fa-thermometer-empty', 'cheatsheet' => 'f2cb;'],
            ['name' => 'fa-thermometer-full', 'cheatsheet' => 'f2c7;'],
            ['name' => 'fa-thermometer-half', 'cheatsheet' => 'f2c9;'],
            ['name' => 'fa-thermometer-quarter', 'cheatsheet' => 'f2ca;'],
            ['name' => 'fa-thermometer-three-quarters', 'cheatsheet' => 'f2c8;'],
            ['name' => 'fa-thumb-tack', 'cheatsheet' => 'f08d;'],
            ['name' => 'fa-thumbs-down', 'cheatsheet' => 'f165;'],
            ['name' => 'fa-thumbs-o-down', 'cheatsheet' => 'f088;'],
            ['name' => 'fa-thumbs-o-up', 'cheatsheet' => 'f087;'],
            ['name' => 'fa-thumbs-up', 'cheatsheet' => 'f164;'],
            ['name' => 'fa-ticket', 'cheatsheet' => 'f145;'],
            ['name' => 'fa-times', 'cheatsheet' => 'f00d;'],
            ['name' => 'fa-times-circle', 'cheatsheet' => 'f057;'],
            ['name' => 'fa-times-circle-o', 'cheatsheet' => 'f05c;'],
            ['name' => 'fa-times-rectangle', 'cheatsheet' => 'f2d3;'],
            ['name' => 'fa-times-rectangle-o', 'cheatsheet' => 'f2d4;'],
            ['name' => 'fa-tint', 'cheatsheet' => 'f043;'],
            ['name' => 'fa-toggle-down', 'cheatsheet' => 'f150;'],
            ['name' => 'fa-toggle-left', 'cheatsheet' => 'f191;'],
            ['name' => 'fa-toggle-off', 'cheatsheet' => 'f204;'],
            ['name' => 'fa-toggle-on', 'cheatsheet' => 'f205;'],
            ['name' => 'fa-toggle-right', 'cheatsheet' => 'f152;'],
            ['name' => 'fa-toggle-up', 'cheatsheet' => 'f151;'],
            ['name' => 'fa-trademark', 'cheatsheet' => 'f25c;'],
            ['name' => 'fa-train', 'cheatsheet' => 'f238;'],
            ['name' => 'fa-transgender', 'cheatsheet' => 'f224;'],
            ['name' => 'fa-transgender-alt', 'cheatsheet' => 'f225;'],
            ['name' => 'fa-trash', 'cheatsheet' => 'f1f8;'],
            ['name' => 'fa-trash-o', 'cheatsheet' => 'f014;'],
            ['name' => 'fa-tree', 'cheatsheet' => 'f1bb;'],
            ['name' => 'fa-trello', 'cheatsheet' => 'f181;'],
            ['name' => 'fa-tripadvisor', 'cheatsheet' => 'f262;'],
            ['name' => 'fa-trophy', 'cheatsheet' => 'f091;'],
            ['name' => 'fa-truck', 'cheatsheet' => 'f0d1;'],
            ['name' => 'fa-try', 'cheatsheet' => 'f195;'],
            ['name' => 'fa-tty', 'cheatsheet' => 'f1e4;'],
            ['name' => 'fa-tumblr', 'cheatsheet' => 'f173;'],
            ['name' => 'fa-tumblr-square', 'cheatsheet' => 'f174;'],
            ['name' => 'fa-turkish-lira', 'cheatsheet' => 'f195;'],
            ['name' => 'fa-tv', 'cheatsheet' => 'f26c;'],
            ['name' => 'fa-twitch', 'cheatsheet' => 'f1e8;'],
            ['name' => 'fa-twitter', 'cheatsheet' => 'f099;'],
            ['name' => 'fa-twitter-square', 'cheatsheet' => 'f081;'],
            ['name' => 'fa-umbrella', 'cheatsheet' => 'f0e9;'],
            ['name' => 'fa-underline', 'cheatsheet' => 'f0cd;'],
            ['name' => 'fa-undo', 'cheatsheet' => 'f0e2;'],
            ['name' => 'fa-universal-access', 'cheatsheet' => 'f29a;'],
            ['name' => 'fa-university', 'cheatsheet' => 'f19c;'],
            ['name' => 'fa-unlink', 'cheatsheet' => 'f127;'],
            ['name' => 'fa-unlock', 'cheatsheet' => 'f09c;'],
            ['name' => 'fa-unlock-alt', 'cheatsheet' => 'f13e;'],
            ['name' => 'fa-unsorted', 'cheatsheet' => 'f0dc;'],
            ['name' => 'fa-upload', 'cheatsheet' => 'f093;'],
            ['name' => 'fa-usb', 'cheatsheet' => 'f287;'],
            ['name' => 'fa-usd', 'cheatsheet' => 'f155;'],
            ['name' => 'fa-user', 'cheatsheet' => 'f007;'],
            ['name' => 'fa-user-circle', 'cheatsheet' => 'f2bd;'],
            ['name' => 'fa-user-circle-o', 'cheatsheet' => 'f2be;'],
            ['name' => 'fa-user-md', 'cheatsheet' => 'f0f0;'],
            ['name' => 'fa-user-o', 'cheatsheet' => 'f2c0;'],
            ['name' => 'fa-user-plus', 'cheatsheet' => 'f234;'],
            ['name' => 'fa-user-secret', 'cheatsheet' => 'f21b;'],
            ['name' => 'fa-user-times', 'cheatsheet' => 'f235;'],
            ['name' => 'fa-users', 'cheatsheet' => 'f0c0;'],
            ['name' => 'fa-vcard', 'cheatsheet' => 'f2bb;'],
            ['name' => 'fa-vcard-o', 'cheatsheet' => 'f2bc;'],
            ['name' => 'fa-venus', 'cheatsheet' => 'f221;'],
            ['name' => 'fa-venus-double', 'cheatsheet' => 'f226;'],
            ['name' => 'fa-venus-mars', 'cheatsheet' => 'f228;'],
            ['name' => 'fa-viacoin', 'cheatsheet' => 'f237;'],
            ['name' => 'fa-viadeo', 'cheatsheet' => 'f2a9;'],
            ['name' => 'fa-viadeo-square', 'cheatsheet' => 'f2aa;'],
            ['name' => 'fa-video-camera', 'cheatsheet' => 'f03d;'],
            ['name' => 'fa-vimeo', 'cheatsheet' => 'f27d;'],
            ['name' => 'fa-vimeo-square', 'cheatsheet' => 'f194;'],
            ['name' => 'fa-vine', 'cheatsheet' => 'f1ca;'],
            ['name' => 'fa-vk', 'cheatsheet' => 'f189;'],
            ['name' => 'fa-volume-control-phone', 'cheatsheet' => 'f2a0;'],
            ['name' => 'fa-volume-down', 'cheatsheet' => 'f027;'],
            ['name' => 'fa-volume-off', 'cheatsheet' => 'f026;'],
            ['name' => 'fa-volume-up', 'cheatsheet' => 'f028;'],
            ['name' => 'fa-warning', 'cheatsheet' => 'f071;'],
            ['name' => 'fa-wechat', 'cheatsheet' => 'f1d7;'],
            ['name' => 'fa-weibo', 'cheatsheet' => 'f18a;'],
            ['name' => 'fa-weixin', 'cheatsheet' => 'f1d7;'],
            ['name' => 'fa-whatsapp', 'cheatsheet' => 'f232;'],
            ['name' => 'fa-wheelchair', 'cheatsheet' => 'f193;'],
            ['name' => 'fa-wheelchair-alt', 'cheatsheet' => 'f29b;'],
            ['name' => 'fa-wifi', 'cheatsheet' => 'f1eb;'],
            ['name' => 'fa-wikipedia-w', 'cheatsheet' => 'f266;'],
            ['name' => 'fa-window-close', 'cheatsheet' => 'f2d3;'],
            ['name' => 'fa-window-close-o', 'cheatsheet' => 'f2d4;'],
            ['name' => 'fa-window-maximize', 'cheatsheet' => 'f2d0;'],
            ['name' => 'fa-window-minimize', 'cheatsheet' => 'f2d1;'],
            ['name' => 'fa-window-restore', 'cheatsheet' => 'f2d2;'],
            ['name' => 'fa-windows', 'cheatsheet' => 'f17a;'],
            ['name' => 'fa-won', 'cheatsheet' => 'f159;'],
            ['name' => 'fa-wordpress', 'cheatsheet' => 'f19a;'],
            ['name' => 'fa-wpbeginner', 'cheatsheet' => 'f297;'],
            ['name' => 'fa-wpexplorer', 'cheatsheet' => 'f2de;'],
            ['name' => 'fa-wpforms', 'cheatsheet' => 'f298;'],
            ['name' => 'fa-wrench', 'cheatsheet' => 'f0ad;'],
            ['name' => 'fa-xing', 'cheatsheet' => 'f168;'],
            ['name' => 'fa-xing-square', 'cheatsheet' => 'f169;'],
            ['name' => 'fa-y-combinator', 'cheatsheet' => 'f23b;'],
            ['name' => 'fa-y-combinator-square', 'cheatsheet' => 'f1d4;'],
            ['name' => 'fa-yahoo', 'cheatsheet' => 'f19e;'],
            ['name' => 'fa-yc', 'cheatsheet' => 'f23b;'],
            ['name' => 'fa-yc-square', 'cheatsheet' => 'f1d4;'],
            ['name' => 'fa-yelp', 'cheatsheet' => 'f1e9;'],
            ['name' => 'fa-yen', 'cheatsheet' => 'f157;'],
            ['name' => 'fa-yoast', 'cheatsheet' => 'f2b1;'],
            ['name' => 'fa-youtube', 'cheatsheet' => 'f167;'],
            ['name' => 'fa-youtube-play', 'cheatsheet' => 'f16a;'],
            ['name' => 'fa-youtube-square', 'cheatsheet' => 'f166;']
        ];

        DB::table('icons')->insert($icon);
    }
}
